// src/tsx/app.tsx
import React, {FC,Fragment} from 'react';

import {Setting} from "./setting";
import { Board } from "./board";
import swal from 'sweetalert';

export const App:FC = () => {

  const board = React.createRef<Board>();
  const setting = React.createRef<Setting>();

  const onclick = ()=>{
    if(board.current && setting.current){
      try{
        const scale = setting.current.state;
        board.current.generateBoard(scale.width, scale.height, scale.mines);
      }catch(e){
        console.log(e);
        console.log(setting.current.state);
      }
      
    }
  };

  return (
		<Fragment>
			<Setting ref = {setting} generate={onclick} />
			<Board ref = {board} />
		</Fragment>
	);
};

// src/vue/app.vue
<template>
	<Setting @generate-event="onclick" />
	<Board :generate="generate" :width="scale.width" :height="scale.height" :mines="scale.mines"/>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from "vue";
import setting from "./setting.vue";
import board from "./board.vue";
import { BoardScale } from "../ts/constants";

export default defineComponent({
	components: {
		Setting: setting,
		Board: board,
	},
	setup() {
		type nullableScale = {
			width?: number;
			height?: number;
			mines?: number;
		};
		const scale = reactive<nullableScale>({
			width:undefined,
			height:undefined,
			mines:undefined,
		});

		const generate = ref(0);
		
		const onclick = (...args: number[]) => {
			const [width, height, mines] = [...args];
			scale.width = width;
			scale.height = height;
			scale.mines = mines;
			generate.value++;
		};

		return {
			scale,
			generate,
			onclick,
		};
	},
});
</script>
